apiVersion: v1
kind: Service
metadata:
  name: slurm-jupyter-service
  namespace: slurm-integration
spec:
  selector:
    app: slurm-jupyter
  ports:
  - protocol: "TCP"
    port: {{ .Values.server.port }}
    targetPort: {{ .Values.server.port }}
  type: LoadBalancer