apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurm-jupyter
  namespace: slurm-integration
spec:
  replicas: {{ .Values.numServers }}
  selector:
    matchLabels:
      app: slurm-jupyter
  template:
    metadata:
      labels:
        app: slurm-jupyter
        name: slurm-jupyter
    spec:
      containers:
        - name: slurm-jupyter
          image: hokiegeek2/slurm-jupyter:{{ .Values.releaseVersion }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.server.resources.requests.cpu }}
              memory: {{ .Values.server.resources.requests.memory }}
            limits:
              cpu: {{ .Values.server.resources.limits.cpu }}
              memory: {{ .Values.server.resources.limits.memory }}
          ports:
          - containerPort: {{ .Values.server.port }}
            hostPort: {{ .Values.server.port }}
          volumeMounts: 
            - name: slurm-config
              mountPath: /etc/slurm-llnl   
            - name: munge-key-file
              mountPath: "/etc/munge"
      volumes:
        - name: slurm-config
          configMap:
            name: slurm-config-map
            items:
             - key: slurm-conf
               path: slurm.conf         
        - name: munge-key-file
          secret:
            secretName: slurm-munge-key   
      